Support for string size constrains and pattern matching
miketonks/swag pull request #7
Opened 2019-02-28 11:05 UTC by Rekfuki

This applies to both scalar strings and arrays of strings.

2019-02-28 12:59 UTC, benpaxton-hf requested changes

2019-02-28 12:59 UTC, benpaxton-hf commented on swagger/reflect.go
> +						p.Items.MaxLength, err = strconv.Atoi(maxLenTag)
See above.

2019-02-28 12:59 UTC, benpaxton-hf commented on swagger/reflect.go
> +					p.MaxLength, err = strconv.Atoi(maxLenTag)
This won't work; if you put `min_length="5" max_length="5"` it'll actually be interpreted as `min=5 min=5`, i.e. no max. Handle them in two separate if statements.

2019-02-28 12:59 UTC, benpaxton-hf commented on swagger/reflect.go
> +		p := inspect(field.Type, field.Tag.Get("json"), field.Tag.Get("format"),
Is it worth just passing `(field.Type, field.Tag)` here? We can still pass `(t, "")` above, since `reflect.StructTag` is just a `string` underneath.

2019-03-05 15:38 UTC, miketonks approved these changes
looks good to me

2019-03-05 15:39 UTC, merged